### ISSUE TITLE
Tabell under grafen

### ISSUE THREAD

**Issue by eribul** [Cstaf/HH_Survival#3]
Från Erik H:

> Går det att under diagrammet få ut en tabell som visar de årsvisa överlevnadssiffrorna med konfídensintervall för de kurvor som visas i diagrammet? Absolut inget som behöver stressas fram denna vecka men på sikt kan det vara snyggt att kunna visa de exakta siffrorna.

Svar från @Cstaf 

> Ser inga problem med att inkludera en tabell med överlevnaden, kan återanvända mycket av skriptet från bilden.

**Comment by eribul** [comment]
Ev lägga överlevnadsuppgifter under grafen (typ 2 st tabeller)

**Comment by Cstaf** [comment]
Är denna issue relevant för HH_survival då vi nu har HC?

**Comment by eribul** [comment]
Instämmer! All info finns ju i grafen så tycker vi stänger den :-)
