### ISSUE TITLE
High charts

### ISSUE THREAD

**Issue by eribul** [Cstaf/HH_Survival#8]
Från Erik H i mail:

> I en senare version hade det också varit snyggt att göra kurvorna med high-chart diagram som Katrin har gjort för sina överlevnadskurvor i lever-galla registret då man med pekaren kan visa siffrorna genom att föra den över grafen. Där kan man också klicka bort eller klicka fram kurvorna.

**Comment by Cstaf** [comment]
Highcharts har nu implementerats på HH överlevnadsrapporten.
